# Site settings
author: Bruce Hillsworth
title: Bruce's Bytes
header-img: img/home-bg.png
email: bruce.hillsworth@gmail.com
copyright_name: Bruce Hillsworth
description: > # this means to ignore newlines until "baseurl:"
  A Full Stack Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hillswor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
